In [7]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from numba import njit, prange
import torch
from graph_optimization import (fastest_averaging_constant_weight,
                                fdla_weights_symmetric, fmmc_weights,
                                lmsc_weights, max_degree_weights,
                                metropolis_hastings_weights)

In [8]:
np.set_printoptions(linewidth=np.inf, threshold=np.inf)

In [9]:
W = np.array([
	[0, 0.33, 0, 0],
	[0.33, 0, 0.33, 0.33],
	[0, 0.33, 0, 0.66],
	[0, 0.33, 0.66, 0]
])

In [10]:
iu = np.triu_indices(W.shape[0], 1)
print(W[iu])

[0.33 0.   0.   0.33 0.33 0.66]


In [13]:
L = W @ np.ones(W.shape[0]) - W
print(L)

[[0.33 0.66 0.99 0.99]
 [0.   0.99 0.66 0.66]
 [0.33 0.66 0.99 0.33]
 [0.33 0.66 0.33 0.99]]


In [16]:
print('W1 = Sw, find S')

print('W1')
print(W @ np.ones(W.shape[0]))
print('w')
w = W[iu]
print(w)

W1 = Sw, find S
W1
[0.33 0.99 0.99 0.99]
w
[0.33 0.   0.   0.33 0.33 0.66]


In [21]:
def calculate_S(n):
	upper_triangular_indices = np.triu_indices(n, k=1)
	S = np.zeros((n, len(upper_triangular_indices[0])))
	S[upper_triangular_indices[0], range(len(upper_triangular_indices[0]))] = 1
	S[upper_triangular_indices[1], range(len(upper_triangular_indices[0]))] = 1
	return S

print(calculate_S(5))

[[1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]]
